language: go

go: 
  - "1.11.x"

sudo: required

env:
  global:
  - PATH=$HOME/.local/bin:$PATH

install:
- curl https://glide.sh/get | sh
- mkdir -p $HOME/.local/bin
- curl -o $HOME/.local/bin/prototool -sSL https://github.com/uber/prototool/releases/download/v0.1.0/prototool-$(uname -s)-$(uname -m)
- chmod +x $HOME/.local/bin/prototool

dist: trusty

services:
  - postgresql

notifications:
  email: false

stages:
  - build
  - lint
  - unit

jobs:
  include:
    - stage: build
      script: scripts/ci.sh build
    - stage: lint
      script: scripts/ci.sh lint
    - stage: unit
      script: scripts/ci.sh unit

matrix:
  include:
  - addons:
      apt:
        packages:
        - rpm
      postgresql: 9.5
  - addons:
      apt:
        packages:
        - rpm
      postgresql: 9.6
