// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v3/clairpb/clair.proto

/*
Package clairpb is a generated protocol buffer package.

It is generated from these files:
	api/v3/clairpb/clair.proto

It has these top-level messages:
	Vulnerability
	Detector
	Namespace
	Feature
	Layer
	ClairStatus
	GetAncestryRequest
	GetAncestryResponse
	PostAncestryRequest
	PostAncestryResponse
	GetNotificationRequest
	GetNotificationResponse
	PagedVulnerableAncestries
	MarkNotificationAsReadRequest
	MarkNotificationAsReadResponse
	GetStatusRequest
	GetStatusResponse
*/
package clairpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Detector_Type int32

const (
	Detector_NAMESPACE Detector_Type = 0
	Detector_FEATURE   Detector_Type = 1
)

var Detector_Type_name = map[int32]string{
	0: "NAMESPACE",
	1: "FEATURE",
}
var Detector_Type_value = map[string]int32{
	"NAMESPACE": 0,
	"FEATURE":   1,
}

func (x Detector_Type) String() string {
	return proto.EnumName(Detector_Type_name, int32(x))
}
func (Detector_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Vulnerability struct {
	// The name of the vulnerability.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The name of the namespace in which the vulnerability was detected.
	NamespaceName string `protobuf:"bytes,2,opt,name=namespace_name,json=namespaceName" json:"namespace_name,omitempty"`
	// A description of the vulnerability according to the source for the namespace.
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// A link to the vulnerability according to the source for the namespace.
	Link string `protobuf:"bytes,4,opt,name=link" json:"link,omitempty"`
	// How dangerous the vulnerability is.
	Severity string `protobuf:"bytes,5,opt,name=severity" json:"severity,omitempty"`
	// Namespace agnostic metadata about the vulnerability.
	Metadata string `protobuf:"bytes,6,opt,name=metadata" json:"metadata,omitempty"`
	// The feature that fixes this vulnerability.
	// This field only exists when a vulnerability is a part of a Feature.
	FixedBy string `protobuf:"bytes,7,opt,name=fixed_by,json=fixedBy" json:"fixed_by,omitempty"`
	// The Features that are affected by the vulnerability.
	// This field only exists when a vulnerability is a part of a Notification.
	AffectedVersions []*Feature `protobuf:"bytes,8,rep,name=affected_versions,json=affectedVersions" json:"affected_versions,omitempty"`
}

func (m *Vulnerability) Reset()                    { *m = Vulnerability{} }
func (m *Vulnerability) String() string            { return proto.CompactTextString(m) }
func (*Vulnerability) ProtoMessage()               {}
func (*Vulnerability) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Vulnerability) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vulnerability) GetNamespaceName() string {
	if m != nil {
		return m.NamespaceName
	}
	return ""
}

func (m *Vulnerability) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Vulnerability) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Vulnerability) GetSeverity() string {
	if m != nil {
		return m.Severity
	}
	return ""
}

func (m *Vulnerability) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *Vulnerability) GetFixedBy() string {
	if m != nil {
		return m.FixedBy
	}
	return ""
}

func (m *Vulnerability) GetAffectedVersions() []*Feature {
	if m != nil {
		return m.AffectedVersions
	}
	return nil
}

type Detector struct {
	// The name of the detector.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The Version of the detector.
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	// The type of the detector.
	Type Detector_Type `protobuf:"varint,3,opt,name=type,enum=coreos.clair.Detector_Type" json:"type,omitempty"`
}

func (m *Detector) Reset()                    { *m = Detector{} }
func (m *Detector) String() string            { return proto.CompactTextString(m) }
func (*Detector) ProtoMessage()               {}
func (*Detector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Detector) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Detector) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Detector) GetType() Detector_Type {
	if m != nil {
		return m.Type
	}
	return Detector_NAMESPACE
}

type Namespace struct {
	// The name of the namespace.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The detector used to detect the namespace.
	Detector *Detector `protobuf:"bytes,2,opt,name=detector" json:"detector,omitempty"`
}

func (m *Namespace) Reset()                    { *m = Namespace{} }
func (m *Namespace) String() string            { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()               {}
func (*Namespace) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Namespace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Namespace) GetDetector() *Detector {
	if m != nil {
		return m.Detector
	}
	return nil
}

type Feature struct {
	// The name of the feature.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The namespace in which the feature is detected.
	Namespace *Namespace `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	// The specific version of this feature.
	Version string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// The format used to parse version numbers for the feature.
	VersionFormat string `protobuf:"bytes,4,opt,name=version_format,json=versionFormat" json:"version_format,omitempty"`
	// The detector used to detect this feature.
	Detector *Detector `protobuf:"bytes,5,opt,name=detector" json:"detector,omitempty"`
	// The list of vulnerabilities that affect the feature.
	Vulnerabilities []*Vulnerability `protobuf:"bytes,6,rep,name=vulnerabilities" json:"vulnerabilities,omitempty"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Feature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feature) GetNamespace() *Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *Feature) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Feature) GetVersionFormat() string {
	if m != nil {
		return m.VersionFormat
	}
	return ""
}

func (m *Feature) GetDetector() *Detector {
	if m != nil {
		return m.Detector
	}
	return nil
}

func (m *Feature) GetVulnerabilities() []*Vulnerability {
	if m != nil {
		return m.Vulnerabilities
	}
	return nil
}

type Layer struct {
	// The sha256 tarsum for the layer.
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *Layer) Reset()                    { *m = Layer{} }
func (m *Layer) String() string            { return proto.CompactTextString(m) }
func (*Layer) ProtoMessage()               {}
func (*Layer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Layer) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type ClairStatus struct {
	// The implemented detectors in this Clair instance
	Detectors []*Detector `protobuf:"bytes,1,rep,name=detectors" json:"detectors,omitempty"`
	// The time at which the updater last ran.
	LastUpdateTime *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=last_update_time,json=lastUpdateTime" json:"last_update_time,omitempty"`
}

func (m *ClairStatus) Reset()                    { *m = ClairStatus{} }
func (m *ClairStatus) String() string            { return proto.CompactTextString(m) }
func (*ClairStatus) ProtoMessage()               {}
func (*ClairStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ClairStatus) GetDetectors() []*Detector {
	if m != nil {
		return m.Detectors
	}
	return nil
}

func (m *ClairStatus) GetLastUpdateTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastUpdateTime
	}
	return nil
}

type GetAncestryRequest struct {
	// The name of the desired ancestry.
	AncestryName string `protobuf:"bytes,1,opt,name=ancestry_name,json=ancestryName" json:"ancestry_name,omitempty"`
}

func (m *GetAncestryRequest) Reset()                    { *m = GetAncestryRequest{} }
func (m *GetAncestryRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAncestryRequest) ProtoMessage()               {}
func (*GetAncestryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetAncestryRequest) GetAncestryName() string {
	if m != nil {
		return m.AncestryName
	}
	return ""
}

type GetAncestryResponse struct {
	// The ancestry requested.
	Ancestry *GetAncestryResponse_Ancestry `protobuf:"bytes,1,opt,name=ancestry" json:"ancestry,omitempty"`
	// The status of Clair at the time of the request.
	Status *ClairStatus `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *GetAncestryResponse) Reset()                    { *m = GetAncestryResponse{} }
func (m *GetAncestryResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAncestryResponse) ProtoMessage()               {}
func (*GetAncestryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetAncestryResponse) GetAncestry() *GetAncestryResponse_Ancestry {
	if m != nil {
		return m.Ancestry
	}
	return nil
}

func (m *GetAncestryResponse) GetStatus() *ClairStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetAncestryResponse_AncestryLayer struct {
	// The layer's information.
	Layer *Layer `protobuf:"bytes,1,opt,name=layer" json:"layer,omitempty"`
	// The features detected in this layer.
	DetectedFeatures []*Feature `protobuf:"bytes,2,rep,name=detected_features,json=detectedFeatures" json:"detected_features,omitempty"`
}

func (m *GetAncestryResponse_AncestryLayer) Reset()         { *m = GetAncestryResponse_AncestryLayer{} }
func (m *GetAncestryResponse_AncestryLayer) String() string { return proto.CompactTextString(m) }
func (*GetAncestryResponse_AncestryLayer) ProtoMessage()    {}
func (*GetAncestryResponse_AncestryLayer) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 0}
}

func (m *GetAncestryResponse_AncestryLayer) GetLayer() *Layer {
	if m != nil {
		return m.Layer
	}
	return nil
}

func (m *GetAncestryResponse_AncestryLayer) GetDetectedFeatures() []*Feature {
	if m != nil {
		return m.DetectedFeatures
	}
	return nil
}

type GetAncestryResponse_Ancestry struct {
	// The name of the desired ancestry.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The detectors used to scan this Ancestry. It maybe not the current set of
	// detectors in clair status.
	Detectors []*Detector `protobuf:"bytes,2,rep,name=detectors" json:"detectors,omitempty"`
	// The list of layers along with detected features in each.
	Layers []*GetAncestryResponse_AncestryLayer `protobuf:"bytes,3,rep,name=layers" json:"layers,omitempty"`
}

func (m *GetAncestryResponse_Ancestry) Reset()                    { *m = GetAncestryResponse_Ancestry{} }
func (m *GetAncestryResponse_Ancestry) String() string            { return proto.CompactTextString(m) }
func (*GetAncestryResponse_Ancestry) ProtoMessage()               {}
func (*GetAncestryResponse_Ancestry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 1} }

func (m *GetAncestryResponse_Ancestry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetAncestryResponse_Ancestry) GetDetectors() []*Detector {
	if m != nil {
		return m.Detectors
	}
	return nil
}

func (m *GetAncestryResponse_Ancestry) GetLayers() []*GetAncestryResponse_AncestryLayer {
	if m != nil {
		return m.Layers
	}
	return nil
}

type PostAncestryRequest struct {
	// The name of the ancestry being scanned.
	// If scanning OCI images, this should be the hash of the manifest.
	AncestryName string `protobuf:"bytes,1,opt,name=ancestry_name,json=ancestryName" json:"ancestry_name,omitempty"`
	// The format of the image being uploaded.
	Format string `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
	// The layers to be scanned for this Ancestry, ordered in the way that i th
	// layer is the parent of i + 1 th layer.
	Layers []*PostAncestryRequest_PostLayer `protobuf:"bytes,3,rep,name=layers" json:"layers,omitempty"`
}

func (m *PostAncestryRequest) Reset()                    { *m = PostAncestryRequest{} }
func (m *PostAncestryRequest) String() string            { return proto.CompactTextString(m) }
func (*PostAncestryRequest) ProtoMessage()               {}
func (*PostAncestryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PostAncestryRequest) GetAncestryName() string {
	if m != nil {
		return m.AncestryName
	}
	return ""
}

func (m *PostAncestryRequest) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *PostAncestryRequest) GetLayers() []*PostAncestryRequest_PostLayer {
	if m != nil {
		return m.Layers
	}
	return nil
}

type PostAncestryRequest_PostLayer struct {
	// The hash of the layer.
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	// The location of the layer (URL or filepath).
	Path string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	// Any HTTP Headers that need to be used if requesting a layer over HTTP(S).
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *PostAncestryRequest_PostLayer) Reset()         { *m = PostAncestryRequest_PostLayer{} }
func (m *PostAncestryRequest_PostLayer) String() string { return proto.CompactTextString(m) }
func (*PostAncestryRequest_PostLayer) ProtoMessage()    {}
func (*PostAncestryRequest_PostLayer) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0}
}

func (m *PostAncestryRequest_PostLayer) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *PostAncestryRequest_PostLayer) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *PostAncestryRequest_PostLayer) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

type PostAncestryResponse struct {
	// The status of Clair at the time of the request.
	Status *ClairStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *PostAncestryResponse) Reset()                    { *m = PostAncestryResponse{} }
func (m *PostAncestryResponse) String() string            { return proto.CompactTextString(m) }
func (*PostAncestryResponse) ProtoMessage()               {}
func (*PostAncestryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PostAncestryResponse) GetStatus() *ClairStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetNotificationRequest struct {
	// The current page of previous vulnerabilities for the ancestry.
	// This will be empty when it is the first page.
	OldVulnerabilityPage string `protobuf:"bytes,1,opt,name=old_vulnerability_page,json=oldVulnerabilityPage" json:"old_vulnerability_page,omitempty"`
	// The current page of vulnerabilities for the ancestry.
	// This will be empty when it is the first page.
	NewVulnerabilityPage string `protobuf:"bytes,2,opt,name=new_vulnerability_page,json=newVulnerabilityPage" json:"new_vulnerability_page,omitempty"`
	// The requested maximum number of results per page.
	Limit int32 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	// The name of the notification being requested.
	Name string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
}

func (m *GetNotificationRequest) Reset()                    { *m = GetNotificationRequest{} }
func (m *GetNotificationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNotificationRequest) ProtoMessage()               {}
func (*GetNotificationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetNotificationRequest) GetOldVulnerabilityPage() string {
	if m != nil {
		return m.OldVulnerabilityPage
	}
	return ""
}

func (m *GetNotificationRequest) GetNewVulnerabilityPage() string {
	if m != nil {
		return m.NewVulnerabilityPage
	}
	return ""
}

func (m *GetNotificationRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetNotificationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetNotificationResponse struct {
	// The notification as requested.
	Notification *GetNotificationResponse_Notification `protobuf:"bytes,1,opt,name=notification" json:"notification,omitempty"`
}

func (m *GetNotificationResponse) Reset()                    { *m = GetNotificationResponse{} }
func (m *GetNotificationResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNotificationResponse) ProtoMessage()               {}
func (*GetNotificationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetNotificationResponse) GetNotification() *GetNotificationResponse_Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

type GetNotificationResponse_Notification struct {
	// The name of the requested notification.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The time at which the notification was created.
	Created string `protobuf:"bytes,2,opt,name=created" json:"created,omitempty"`
	// The time at which the notification was last sent out.
	Notified string `protobuf:"bytes,3,opt,name=notified" json:"notified,omitempty"`
	// The time at which a notification has been deleted.
	Deleted string `protobuf:"bytes,4,opt,name=deleted" json:"deleted,omitempty"`
	// The previous vulnerability and a paginated view of the ancestries it affects.
	Old *PagedVulnerableAncestries `protobuf:"bytes,5,opt,name=old" json:"old,omitempty"`
	// The newly updated vulnerability and a paginated view of the ancestries it affects.
	New *PagedVulnerableAncestries `protobuf:"bytes,6,opt,name=new" json:"new,omitempty"`
}

func (m *GetNotificationResponse_Notification) Reset()         { *m = GetNotificationResponse_Notification{} }
func (m *GetNotificationResponse_Notification) String() string { return proto.CompactTextString(m) }
func (*GetNotificationResponse_Notification) ProtoMessage()    {}
func (*GetNotificationResponse_Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11, 0}
}

func (m *GetNotificationResponse_Notification) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetNotificationResponse_Notification) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *GetNotificationResponse_Notification) GetNotified() string {
	if m != nil {
		return m.Notified
	}
	return ""
}

func (m *GetNotificationResponse_Notification) GetDeleted() string {
	if m != nil {
		return m.Deleted
	}
	return ""
}

func (m *GetNotificationResponse_Notification) GetOld() *PagedVulnerableAncestries {
	if m != nil {
		return m.Old
	}
	return nil
}

func (m *GetNotificationResponse_Notification) GetNew() *PagedVulnerableAncestries {
	if m != nil {
		return m.New
	}
	return nil
}

type PagedVulnerableAncestries struct {
	// The identifier for the current page.
	CurrentPage string `protobuf:"bytes,1,opt,name=current_page,json=currentPage" json:"current_page,omitempty"`
	// The token used to request the next page.
	// This will be empty when there are no more pages.
	NextPage string `protobuf:"bytes,2,opt,name=next_page,json=nextPage" json:"next_page,omitempty"`
	// The requested maximum number of results per page.
	Limit int32 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	// The vulnerability that affects a given set of ancestries.
	Vulnerability *Vulnerability `protobuf:"bytes,4,opt,name=vulnerability" json:"vulnerability,omitempty"`
	// The ancestries affected by a vulnerability.
	Ancestries []*PagedVulnerableAncestries_IndexedAncestryName `protobuf:"bytes,5,rep,name=ancestries" json:"ancestries,omitempty"`
}

func (m *PagedVulnerableAncestries) Reset()                    { *m = PagedVulnerableAncestries{} }
func (m *PagedVulnerableAncestries) String() string            { return proto.CompactTextString(m) }
func (*PagedVulnerableAncestries) ProtoMessage()               {}
func (*PagedVulnerableAncestries) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PagedVulnerableAncestries) GetCurrentPage() string {
	if m != nil {
		return m.CurrentPage
	}
	return ""
}

func (m *PagedVulnerableAncestries) GetNextPage() string {
	if m != nil {
		return m.NextPage
	}
	return ""
}

func (m *PagedVulnerableAncestries) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PagedVulnerableAncestries) GetVulnerability() *Vulnerability {
	if m != nil {
		return m.Vulnerability
	}
	return nil
}

func (m *PagedVulnerableAncestries) GetAncestries() []*PagedVulnerableAncestries_IndexedAncestryName {
	if m != nil {
		return m.Ancestries
	}
	return nil
}

type PagedVulnerableAncestries_IndexedAncestryName struct {
	// The index is an ever increasing number associated with the particular ancestry.
	// This is useful if you're processing notifications, and need to keep track of the progress of paginating the results.
	Index int32 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	// The name of the ancestry.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *PagedVulnerableAncestries_IndexedAncestryName) Reset() {
	*m = PagedVulnerableAncestries_IndexedAncestryName{}
}
func (m *PagedVulnerableAncestries_IndexedAncestryName) String() string {
	return proto.CompactTextString(m)
}
func (*PagedVulnerableAncestries_IndexedAncestryName) ProtoMessage() {}
func (*PagedVulnerableAncestries_IndexedAncestryName) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{12, 0}
}

func (m *PagedVulnerableAncestries_IndexedAncestryName) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *PagedVulnerableAncestries_IndexedAncestryName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MarkNotificationAsReadRequest struct {
	// The name of the Notification that has been processed.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MarkNotificationAsReadRequest) Reset()                    { *m = MarkNotificationAsReadRequest{} }
func (m *MarkNotificationAsReadRequest) String() string            { return proto.CompactTextString(m) }
func (*MarkNotificationAsReadRequest) ProtoMessage()               {}
func (*MarkNotificationAsReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *MarkNotificationAsReadRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MarkNotificationAsReadResponse struct {
}

func (m *MarkNotificationAsReadResponse) Reset()                    { *m = MarkNotificationAsReadResponse{} }
func (m *MarkNotificationAsReadResponse) String() string            { return proto.CompactTextString(m) }
func (*MarkNotificationAsReadResponse) ProtoMessage()               {}
func (*MarkNotificationAsReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type GetStatusRequest struct {
}

func (m *GetStatusRequest) Reset()                    { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()               {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type GetStatusResponse struct {
	// The status of the current Clair instance.
	Status *ClairStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *GetStatusResponse) Reset()                    { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()               {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetStatusResponse) GetStatus() *ClairStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Vulnerability)(nil), "coreos.clair.Vulnerability")
	proto.RegisterType((*Detector)(nil), "coreos.clair.Detector")
	proto.RegisterType((*Namespace)(nil), "coreos.clair.Namespace")
	proto.RegisterType((*Feature)(nil), "coreos.clair.Feature")
	proto.RegisterType((*Layer)(nil), "coreos.clair.Layer")
	proto.RegisterType((*ClairStatus)(nil), "coreos.clair.ClairStatus")
	proto.RegisterType((*GetAncestryRequest)(nil), "coreos.clair.GetAncestryRequest")
	proto.RegisterType((*GetAncestryResponse)(nil), "coreos.clair.GetAncestryResponse")
	proto.RegisterType((*GetAncestryResponse_AncestryLayer)(nil), "coreos.clair.GetAncestryResponse.AncestryLayer")
	proto.RegisterType((*GetAncestryResponse_Ancestry)(nil), "coreos.clair.GetAncestryResponse.Ancestry")
	proto.RegisterType((*PostAncestryRequest)(nil), "coreos.clair.PostAncestryRequest")
	proto.RegisterType((*PostAncestryRequest_PostLayer)(nil), "coreos.clair.PostAncestryRequest.PostLayer")
	proto.RegisterType((*PostAncestryResponse)(nil), "coreos.clair.PostAncestryResponse")
	proto.RegisterType((*GetNotificationRequest)(nil), "coreos.clair.GetNotificationRequest")
	proto.RegisterType((*GetNotificationResponse)(nil), "coreos.clair.GetNotificationResponse")
	proto.RegisterType((*GetNotificationResponse_Notification)(nil), "coreos.clair.GetNotificationResponse.Notification")
	proto.RegisterType((*PagedVulnerableAncestries)(nil), "coreos.clair.PagedVulnerableAncestries")
	proto.RegisterType((*PagedVulnerableAncestries_IndexedAncestryName)(nil), "coreos.clair.PagedVulnerableAncestries.IndexedAncestryName")
	proto.RegisterType((*MarkNotificationAsReadRequest)(nil), "coreos.clair.MarkNotificationAsReadRequest")
	proto.RegisterType((*MarkNotificationAsReadResponse)(nil), "coreos.clair.MarkNotificationAsReadResponse")
	proto.RegisterType((*GetStatusRequest)(nil), "coreos.clair.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "coreos.clair.GetStatusResponse")
	proto.RegisterEnum("coreos.clair.Detector_Type", Detector_Type_name, Detector_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AncestryService service

type AncestryServiceClient interface {
	// The RPC used to read the results of scanning for a particular ancestry.
	GetAncestry(ctx context.Context, in *GetAncestryRequest, opts ...grpc.CallOption) (*GetAncestryResponse, error)
	// The RPC used to create a new scan of an ancestry.
	PostAncestry(ctx context.Context, in *PostAncestryRequest, opts ...grpc.CallOption) (*PostAncestryResponse, error)
}

type ancestryServiceClient struct {
	cc *grpc.ClientConn
}

func NewAncestryServiceClient(cc *grpc.ClientConn) AncestryServiceClient {
	return &ancestryServiceClient{cc}
}

func (c *ancestryServiceClient) GetAncestry(ctx context.Context, in *GetAncestryRequest, opts ...grpc.CallOption) (*GetAncestryResponse, error) {
	out := new(GetAncestryResponse)
	err := grpc.Invoke(ctx, "/coreos.clair.AncestryService/GetAncestry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ancestryServiceClient) PostAncestry(ctx context.Context, in *PostAncestryRequest, opts ...grpc.CallOption) (*PostAncestryResponse, error) {
	out := new(PostAncestryResponse)
	err := grpc.Invoke(ctx, "/coreos.clair.AncestryService/PostAncestry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AncestryService service

type AncestryServiceServer interface {
	// The RPC used to read the results of scanning for a particular ancestry.
	GetAncestry(context.Context, *GetAncestryRequest) (*GetAncestryResponse, error)
	// The RPC used to create a new scan of an ancestry.
	PostAncestry(context.Context, *PostAncestryRequest) (*PostAncestryResponse, error)
}

func RegisterAncestryServiceServer(s *grpc.Server, srv AncestryServiceServer) {
	s.RegisterService(&_AncestryService_serviceDesc, srv)
}

func _AncestryService_GetAncestry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAncestryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AncestryServiceServer).GetAncestry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coreos.clair.AncestryService/GetAncestry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AncestryServiceServer).GetAncestry(ctx, req.(*GetAncestryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AncestryService_PostAncestry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostAncestryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AncestryServiceServer).PostAncestry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coreos.clair.AncestryService/PostAncestry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AncestryServiceServer).PostAncestry(ctx, req.(*PostAncestryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AncestryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "coreos.clair.AncestryService",
	HandlerType: (*AncestryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAncestry",
			Handler:    _AncestryService_GetAncestry_Handler,
		},
		{
			MethodName: "PostAncestry",
			Handler:    _AncestryService_PostAncestry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v3/clairpb/clair.proto",
}

// Client API for NotificationService service

type NotificationServiceClient interface {
	// The RPC used to get a particularly Notification.
	GetNotification(ctx context.Context, in *GetNotificationRequest, opts ...grpc.CallOption) (*GetNotificationResponse, error)
	// The RPC used to mark a Notification as read after it has been processed.
	MarkNotificationAsRead(ctx context.Context, in *MarkNotificationAsReadRequest, opts ...grpc.CallOption) (*MarkNotificationAsReadResponse, error)
}

type notificationServiceClient struct {
	cc *grpc.ClientConn
}

func NewNotificationServiceClient(cc *grpc.ClientConn) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) GetNotification(ctx context.Context, in *GetNotificationRequest, opts ...grpc.CallOption) (*GetNotificationResponse, error) {
	out := new(GetNotificationResponse)
	err := grpc.Invoke(ctx, "/coreos.clair.NotificationService/GetNotification", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) MarkNotificationAsRead(ctx context.Context, in *MarkNotificationAsReadRequest, opts ...grpc.CallOption) (*MarkNotificationAsReadResponse, error) {
	out := new(MarkNotificationAsReadResponse)
	err := grpc.Invoke(ctx, "/coreos.clair.NotificationService/MarkNotificationAsRead", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NotificationService service

type NotificationServiceServer interface {
	// The RPC used to get a particularly Notification.
	GetNotification(context.Context, *GetNotificationRequest) (*GetNotificationResponse, error)
	// The RPC used to mark a Notification as read after it has been processed.
	MarkNotificationAsRead(context.Context, *MarkNotificationAsReadRequest) (*MarkNotificationAsReadResponse, error)
}

func RegisterNotificationServiceServer(s *grpc.Server, srv NotificationServiceServer) {
	s.RegisterService(&_NotificationService_serviceDesc, srv)
}

func _NotificationService_GetNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coreos.clair.NotificationService/GetNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetNotification(ctx, req.(*GetNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_MarkNotificationAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationAsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).MarkNotificationAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coreos.clair.NotificationService/MarkNotificationAsRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).MarkNotificationAsRead(ctx, req.(*MarkNotificationAsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotificationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "coreos.clair.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNotification",
			Handler:    _NotificationService_GetNotification_Handler,
		},
		{
			MethodName: "MarkNotificationAsRead",
			Handler:    _NotificationService_MarkNotificationAsRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v3/clairpb/clair.proto",
}

// Client API for StatusService service

type StatusServiceClient interface {
	// The RPC used to show the internal state of current Clair instance.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
}

type statusServiceClient struct {
	cc *grpc.ClientConn
}

func NewStatusServiceClient(cc *grpc.ClientConn) StatusServiceClient {
	return &statusServiceClient{cc}
}

func (c *statusServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := grpc.Invoke(ctx, "/coreos.clair.StatusService/GetStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StatusService service

type StatusServiceServer interface {
	// The RPC used to show the internal state of current Clair instance.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
}

func RegisterStatusServiceServer(s *grpc.Server, srv StatusServiceServer) {
	s.RegisterService(&_StatusService_serviceDesc, srv)
}

func _StatusService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coreos.clair.StatusService/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StatusService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "coreos.clair.StatusService",
	HandlerType: (*StatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _StatusService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v3/clairpb/clair.proto",
}

func init() { proto.RegisterFile("api/v3/clairpb/clair.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xcd, 0x6e, 0x1b, 0xd5,
	0x17, 0xff, 0x8f, 0x1d, 0xc7, 0xf6, 0xb1, 0x9d, 0xa4, 0x37, 0x69, 0xea, 0x4c, 0xfe, 0x6d, 0x93,
	0x81, 0x8a, 0x52, 0x90, 0x2d, 0xdc, 0x22, 0xb5, 0x65, 0x81, 0xdc, 0x36, 0x09, 0x95, 0x68, 0x54,
	0x4d, 0xda, 0x2e, 0x40, 0xc8, 0xba, 0xf1, 0x1c, 0x27, 0xa3, 0x8c, 0x67, 0x86, 0x99, 0xeb, 0x24,
	0x56, 0x55, 0x16, 0xec, 0x58, 0x20, 0x21, 0x58, 0xb0, 0xe2, 0x01, 0xd8, 0x20, 0xde, 0x81, 0x37,
	0x80, 0x2d, 0xec, 0x58, 0xf0, 0x02, 0xec, 0xd1, 0xfd, 0x9a, 0xcc, 0x38, 0x93, 0xc4, 0xed, 0xca,
	0xf7, 0x9e, 0x7b, 0xbe, 0xcf, 0xef, 0x9c, 0x33, 0x06, 0x93, 0x86, 0x6e, 0xfb, 0xf0, 0x76, 0xbb,
	0xef, 0x51, 0x37, 0x0a, 0x77, 0xe5, 0x6f, 0x2b, 0x8c, 0x02, 0x16, 0x90, 0x7a, 0x3f, 0x88, 0x30,
	0x88, 0x5b, 0x82, 0x66, 0x5e, 0xdf, 0x0b, 0x82, 0x3d, 0x0f, 0xdb, 0xe2, 0x6d, 0x77, 0x34, 0x68,
	0x33, 0x77, 0x88, 0x31, 0xa3, 0xc3, 0x50, 0xb2, 0x9b, 0xff, 0x57, 0x0c, 0x5c, 0x23, 0xf5, 0xfd,
	0x80, 0x51, 0xe6, 0x06, 0x7e, 0x2c, 0x5f, 0xad, 0x1f, 0x0b, 0xd0, 0x78, 0x31, 0xf2, 0x7c, 0x8c,
	0xe8, 0xae, 0xeb, 0xb9, 0x6c, 0x4c, 0x08, 0xcc, 0xf8, 0x74, 0x88, 0x4d, 0x63, 0xcd, 0xb8, 0x59,
	0xb5, 0xc5, 0x99, 0xdc, 0x80, 0x39, 0xfe, 0x1b, 0x87, 0xb4, 0x8f, 0x3d, 0xf1, 0x5a, 0x10, 0xaf,
	0x8d, 0x84, 0xba, 0xcd, 0xd9, 0xd6, 0xa0, 0xe6, 0x60, 0xdc, 0x8f, 0xdc, 0x90, 0x9b, 0x68, 0x16,
	0x05, 0x4f, 0x9a, 0xc4, 0x95, 0x7b, 0xae, 0x7f, 0xd0, 0x9c, 0x91, 0xca, 0xf9, 0x99, 0x98, 0x50,
	0x89, 0xf1, 0x10, 0x23, 0x97, 0x8d, 0x9b, 0x25, 0x41, 0x4f, 0xee, 0xfc, 0x6d, 0x88, 0x8c, 0x3a,
	0x94, 0xd1, 0xe6, 0xac, 0x7c, 0xd3, 0x77, 0xb2, 0x02, 0x95, 0x81, 0x7b, 0x8c, 0x4e, 0x6f, 0x77,
	0xdc, 0x2c, 0x8b, 0xb7, 0xb2, 0xb8, 0x3f, 0x18, 0x93, 0x07, 0x70, 0x89, 0x0e, 0x06, 0xd8, 0x67,
	0xe8, 0xf4, 0x0e, 0x31, 0x8a, 0x79, 0xc0, 0xcd, 0xca, 0x5a, 0xf1, 0x66, 0xad, 0x73, 0xb9, 0x95,
	0x4e, 0x5f, 0x6b, 0x13, 0x29, 0x1b, 0x45, 0x68, 0x2f, 0x68, 0xfe, 0x17, 0x8a, 0xdd, 0xfa, 0xd6,
	0x80, 0xca, 0x23, 0x64, 0xd8, 0x67, 0x41, 0x94, 0x9b, 0x94, 0x26, 0x94, 0x95, 0x6e, 0x95, 0x0d,
	0x7d, 0x25, 0x6d, 0x98, 0x61, 0xe3, 0x10, 0x45, 0x02, 0xe6, 0x3a, 0xab, 0x59, 0x8b, 0x5a, 0x67,
	0xeb, 0xd9, 0x38, 0x44, 0x5b, 0x30, 0x5a, 0x16, 0xcc, 0xf0, 0x1b, 0x69, 0x40, 0x75, 0xbb, 0xfb,
	0x64, 0x63, 0xe7, 0x69, 0xf7, 0xe1, 0xc6, 0xc2, 0xff, 0x48, 0x0d, 0xca, 0x9b, 0x1b, 0xdd, 0x67,
	0xcf, 0xed, 0x8d, 0x05, 0xc3, 0xda, 0x81, 0xea, 0xb6, 0xce, 0x76, 0xae, 0x3f, 0x1d, 0xa8, 0x38,
	0x4a, 0xb7, 0x70, 0xa8, 0xd6, 0x59, 0xce, 0xb7, 0x6c, 0x27, 0x7c, 0xd6, 0x77, 0x05, 0x28, 0xab,
	0x14, 0xe4, 0xea, 0xfc, 0x10, 0xaa, 0x49, 0x89, 0x95, 0xd2, 0x2b, 0x59, 0xa5, 0x89, 0x4f, 0xf6,
	0x09, 0x67, 0x3a, 0x35, 0xc5, 0x6c, 0x6a, 0x6e, 0xc0, 0x9c, 0x3a, 0xf6, 0x06, 0x41, 0x34, 0xa4,
	0x4c, 0x41, 0xa1, 0xa1, 0xa8, 0x9b, 0x82, 0x98, 0x89, 0xa5, 0x34, 0x5d, 0x2c, 0x64, 0x03, 0xe6,
	0x0f, 0x53, 0x48, 0x76, 0x31, 0x6e, 0xce, 0x8a, 0x92, 0x4f, 0x14, 0x20, 0x03, 0x77, 0x7b, 0x52,
	0xc6, 0x5a, 0x85, 0xd2, 0xa7, 0x74, 0x8c, 0xa2, 0xe6, 0xfb, 0x34, 0xde, 0xd7, 0xf9, 0xe0, 0x67,
	0xeb, 0x1b, 0x03, 0x6a, 0x0f, 0xb9, 0x96, 0x1d, 0x46, 0xd9, 0x28, 0x26, 0x77, 0xa0, 0xaa, 0xed,
	0xc7, 0x4d, 0x43, 0x58, 0x3b, 0xcb, 0xd1, 0x13, 0x46, 0xf2, 0x08, 0x16, 0x3c, 0x1a, 0xb3, 0xde,
	0x28, 0x74, 0x28, 0xc3, 0x1e, 0xef, 0x58, 0x95, 0x5c, 0xb3, 0x25, 0xbb, 0xb5, 0xa5, 0xdb, 0xb9,
	0xf5, 0x4c, 0xb7, 0xb3, 0x3d, 0xc7, 0x65, 0x9e, 0x0b, 0x11, 0x4e, 0xb4, 0xee, 0x01, 0xd9, 0x42,
	0xd6, 0xf5, 0xfb, 0x18, 0xb3, 0x68, 0x6c, 0xe3, 0x97, 0x23, 0x8c, 0x19, 0x79, 0x0b, 0x1a, 0x54,
	0x91, 0x7a, 0xa9, 0x72, 0xd6, 0x35, 0x91, 0xd7, 0xcb, 0xfa, 0xb5, 0x08, 0x8b, 0x19, 0xd9, 0x38,
	0x0c, 0xfc, 0x18, 0xc9, 0x26, 0x54, 0x34, 0x9f, 0x90, 0xab, 0x75, 0x6e, 0x65, 0xa3, 0xc9, 0x11,
	0x6a, 0x25, 0x84, 0x44, 0x96, 0x7c, 0x00, 0xb3, 0xb1, 0x48, 0x90, 0x0a, 0x6b, 0x25, 0xab, 0x25,
	0x95, 0x41, 0x5b, 0x31, 0x9a, 0x5f, 0x41, 0x43, 0x2b, 0x92, 0xe9, 0x7f, 0x17, 0x4a, 0x1e, 0x3f,
	0x28, 0x47, 0x16, 0xb3, 0x2a, 0x04, 0x8f, 0x2d, 0x39, 0x78, 0xbb, 0xcb, 0xe4, 0xa2, 0xd3, 0x1b,
	0x48, 0x34, 0x73, 0xcb, 0xe7, 0xb5, 0xbb, 0xe6, 0x57, 0x84, 0xd8, 0xfc, 0xc9, 0x80, 0x8a, 0x76,
	0x20, 0xb7, 0x15, 0x32, 0xa5, 0x2e, 0x4c, 0x5b, 0xea, 0x2d, 0x98, 0x15, 0x3e, 0xc6, 0xcd, 0xa2,
	0x10, 0x69, 0x4f, 0x9f, 0x4f, 0x19, 0xa2, 0x12, 0xb7, 0xfe, 0x2a, 0xc0, 0xe2, 0xd3, 0x20, 0x7e,
	0xa3, 0x7a, 0x93, 0x65, 0x98, 0x55, 0xdd, 0x26, 0x27, 0x95, 0xba, 0x91, 0x87, 0x13, 0xde, 0xbd,
	0x97, 0xf5, 0x2e, 0xc7, 0x9e, 0xa0, 0x65, 0x3c, 0x33, 0x7f, 0x33, 0xa0, 0x9a, 0x50, 0xf3, 0xba,
	0x86, 0xd3, 0x42, 0xca, 0xf6, 0x95, 0x71, 0x71, 0x26, 0x36, 0x94, 0xf7, 0x91, 0x3a, 0x27, 0xb6,
	0xef, 0xbe, 0x86, 0xed, 0xd6, 0x27, 0x52, 0x74, 0xc3, 0xe7, 0xaf, 0x5a, 0x91, 0x79, 0x1f, 0xea,
	0xe9, 0x07, 0xb2, 0x00, 0xc5, 0x03, 0x1c, 0x2b, 0x57, 0xf8, 0x91, 0x2c, 0x41, 0xe9, 0x90, 0x7a,
	0x23, 0xbd, 0xbf, 0xe4, 0xe5, 0x7e, 0xe1, 0xae, 0x61, 0x3d, 0x86, 0xa5, 0xac, 0x49, 0xd5, 0x12,
	0x27, 0x50, 0x36, 0xa6, 0x84, 0xb2, 0xf5, 0x8b, 0x01, 0xcb, 0x5b, 0xc8, 0xb6, 0x03, 0xe6, 0x0e,
	0xdc, 0xbe, 0x58, 0xb7, 0xba, 0x5a, 0x77, 0x60, 0x39, 0xf0, 0x9c, 0x5e, 0x7a, 0xe6, 0x8c, 0x7b,
	0x21, 0xdd, 0xd3, 0x65, 0x5b, 0x0a, 0x3c, 0x27, 0x33, 0x9f, 0x9e, 0xd2, 0x3d, 0x0e, 0xbd, 0x65,
	0x1f, 0x8f, 0xf2, 0xa4, 0x64, 0x18, 0x4b, 0x3e, 0x1e, 0x9d, 0x96, 0x5a, 0x82, 0x92, 0xe7, 0x0e,
	0x5d, 0x26, 0x46, 0x70, 0xc9, 0x96, 0x97, 0x04, 0xda, 0x33, 0x27, 0xd0, 0xb6, 0xfe, 0x2c, 0xc0,
	0x95, 0x53, 0x0e, 0xab, 0xf8, 0x5f, 0x40, 0xdd, 0x4f, 0xd1, 0x55, 0x16, 0x3a, 0xa7, 0x60, 0x9c,
	0x27, 0xdc, 0xca, 0x10, 0x33, 0x7a, 0xcc, 0x7f, 0x0c, 0xa8, 0xa7, 0x9f, 0xcf, 0x5a, 0xb1, 0xfd,
	0x08, 0x29, 0x43, 0x47, 0xaf, 0x58, 0x75, 0xe5, 0x1f, 0x06, 0x52, 0x1d, 0x3a, 0x6a, 0xc5, 0x24,
	0x77, 0x2e, 0xe5, 0xa0, 0x87, 0x5c, 0x4a, 0x46, 0xa9, 0xaf, 0xe4, 0x1e, 0x14, 0x03, 0xcf, 0x51,
	0x1b, 0xe5, 0x9d, 0x09, 0xc0, 0xd1, 0x3d, 0x4c, 0x72, 0xef, 0xa1, 0x02, 0x82, 0x8b, 0xb1, 0xcd,
	0x65, 0xb8, 0xa8, 0x8f, 0x47, 0xe2, 0x23, 0xe4, 0x75, 0x44, 0x7d, 0x3c, 0xb2, 0x7e, 0x2f, 0xc0,
	0xca, 0x99, 0x2c, 0x64, 0x1d, 0xea, 0xfd, 0x51, 0x14, 0xa1, 0xcf, 0xd2, 0x40, 0xa8, 0x29, 0x9a,
	0xa8, 0xe4, 0x2a, 0x54, 0x7d, 0x3c, 0x66, 0xe9, 0x92, 0x57, 0x38, 0xe1, 0x9c, 0x32, 0x77, 0xa1,
	0x91, 0x81, 0x8b, 0xc8, 0xc4, 0x05, 0xab, 0x30, 0x2b, 0x41, 0x3e, 0x07, 0xa0, 0x89, 0x9b, 0xcd,
	0x92, 0x68, 0xd2, 0x8f, 0xa6, 0x0c, 0xbc, 0xf5, 0xd8, 0x77, 0xf0, 0x18, 0x9d, 0x6e, 0x6a, 0x0a,
	0xd9, 0x29, 0x75, 0xe6, 0xc7, 0xb0, 0x98, 0xc3, 0xc2, 0x83, 0x71, 0x39, 0x59, 0x64, 0xa1, 0x64,
	0xcb, 0x4b, 0x02, 0x8d, 0x42, 0x0a, 0xb3, 0xb7, 0xe1, 0xea, 0x13, 0x1a, 0x1d, 0xa4, 0x21, 0xd4,
	0x8d, 0x6d, 0xa4, 0x8e, 0x6e, 0xb5, 0x1c, 0x3c, 0x59, 0x6b, 0x70, 0xed, 0x2c, 0x21, 0x89, 0x58,
	0x8b, 0xc0, 0xc2, 0x16, 0x32, 0xd5, 0xd0, 0x52, 0x93, 0xb5, 0x09, 0x97, 0x52, 0xb4, 0x37, 0x9e,
	0x0b, 0x9d, 0x7f, 0x0d, 0x98, 0xd7, 0xd1, 0xee, 0x60, 0x74, 0xe8, 0xf6, 0x91, 0x8c, 0xa0, 0x96,
	0xda, 0x01, 0x64, 0xed, 0x9c, 0xf5, 0x20, 0x9c, 0x31, 0xd7, 0x2f, 0x5c, 0x20, 0xd6, 0xfa, 0xd7,
	0x7f, 0xfc, 0xfd, 0x43, 0x61, 0x95, 0xac, 0xb4, 0xf5, 0x12, 0x68, 0xbf, 0xcc, 0xec, 0x88, 0x57,
	0xe4, 0x00, 0xea, 0xe9, 0x69, 0x47, 0xd6, 0x2f, 0x1c, 0xbe, 0xa6, 0x75, 0x1e, 0x8b, 0xb2, 0xbc,
	0x24, 0x2c, 0xcf, 0x59, 0xd5, 0xc4, 0xf2, 0x7d, 0xe3, 0x56, 0xe7, 0xe7, 0x02, 0x2c, 0xa6, 0x53,
	0xae, 0x63, 0x7f, 0x05, 0xf3, 0x13, 0x83, 0x83, 0xbc, 0x7d, 0xc1, 0x5c, 0x91, 0xae, 0xdc, 0x98,
	0x6a, 0xfa, 0x58, 0x57, 0x85, 0x37, 0x57, 0xc8, 0xe5, 0x76, 0x7a, 0xf2, 0xc4, 0xed, 0x97, 0x32,
	0x07, 0xdf, 0x1b, 0xb0, 0x9c, 0x8f, 0x06, 0x32, 0xb1, 0x07, 0xcf, 0x05, 0x9a, 0xf9, 0xfe, 0x74,
	0xcc, 0x59, 0xa7, 0x6e, 0xe5, 0x3b, 0xd5, 0xf1, 0xa1, 0x21, 0x51, 0xa3, 0x93, 0xf4, 0x05, 0x54,
	0x13, 0xf0, 0x91, 0x6b, 0xa7, 0x02, 0xcf, 0x20, 0xd5, 0xbc, 0x7e, 0xe6, 0xbb, 0xb2, 0x3e, 0x2f,
	0xac, 0x57, 0x49, 0xb9, 0x2d, 0x31, 0xf9, 0xe0, 0x1a, 0x2c, 0xf6, 0x83, 0x61, 0x56, 0x2c, 0xdc,
	0xfd, 0xac, 0xac, 0xfe, 0x78, 0xee, 0xce, 0x8a, 0x0f, 0xd1, 0xdb, 0xff, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x2f, 0x60, 0x88, 0x26, 0x91, 0x0e, 0x00, 0x00,
}
